version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: jobtracker-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password // can be read from .env like env_file - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - jobtracker-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobtracker-app
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/jobtracker?authSource=admin
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - jobtracker-network
    restart: unless-stopped

networks:
  jobtracker-network:
    driver: bridge

volumes:
  mongodb_data:
