spring:
  application:
    name: jobTracker
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/jobtracker?authSource=admin

server:
  port: 8080

# Custom CORS configuration
cors:
  allowed-origins: http://localhost:3000,http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600
